### ISSUE TITLE
ArgumentArityError error

### ISSUE THREAD

**Issue by mahmoud** [mahmoud/face#11]
```
$ pprotect decrypt-domain -h
Traceback (most recent call last):
  File "/home/mahmoud/virtualenvs/tmp-a8562a6efb19e34/lib/python3.5/site-packages/face/command.py", line 357, in run
    prs_res = self.parse(argv=argv)
  File "/home/mahmoud/virtualenvs/tmp-a8562a6efb19e34/lib/python3.5/site-packages/face/parser.py", line 774, in parse
    parsed_posargs = prs.posargs.parse(posargs)
  File "/home/mahmoud/virtualenvs/tmp-a8562a6efb19e34/lib/python3.5/site-packages/face/parser.py", line 486, in parse
    % (arg_range_text, len_posargs))
face.errors.ArgumentArityError: too few arguments, expected 1 argument, got 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mahmoud/virtualenvs/tmp-a8562a6efb19e34/bin/pprotect", line 8, in <module>
    sys.exit(main())
  File "/home/mahmoud/virtualenvs/tmp-a8562a6efb19e34/lib/python3.5/site-packages/pocket_protector/cli.py", line 201, in main
    cmd.run(argv=argv)  # exit behavior is handled by mw_exit_handler
  File "/home/mahmoud/virtualenvs/tmp-a8562a6efb19e34/lib/python3.5/site-packages/face/command.py", line 365, in run
    return inject(cmd.help_handler.func, kwargs)
  File "/home/mahmoud/virtualenvs/tmp-a8562a6efb19e34/lib/python3.5/site-packages/face/sinter.py", line 59, in inject
    return f(**kwargs)
  File "/home/mahmoud/virtualenvs/tmp-a8562a6efb19e34/lib/python3.5/site-packages/face/helpers.py", line 429, in default_help_func
    echo(self.formatter.get_help_text(command_, subcmds=subcmds_, program_name=cmd_))
  File "/home/mahmoud/virtualenvs/tmp-a8562a6efb19e34/lib/python3.5/site-packages/face/helpers.py", line 249, in get_help_text
    ret = [self.get_usage_line(parser, subcmds=subcmds, program_name=program_name)]
  File "/home/mahmoud/virtualenvs/tmp-a8562a6efb19e34/lib/python3.5/site-packages/face/helpers.py", line 348, in get_usage_line
    append(fmt_posargs_label(parser.posargs))
  File "/home/mahmoud/virtualenvs/tmp-a8562a6efb19e34/lib/python3.5/site-packages/face/utils.py", line 133, in format_posargs_label
    return get_cardinalized_args_label(posargspec.display.name, posargspec.min_count, posargspec.max_count)
  File "/home/mahmoud/virtualenvs/tmp-a8562a6efb19e34/lib/python3.5/site-packages/face/utils.py", line 146, in get_cardinalized_args_label
    return ' '.join([name] * min_count)
TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by mahmoud** [comment]
Quick post-script on this: The Arity error was actually intentional/expected, but the display name of the posargspec wasn't being propagated. This is fixed in face now, and the related improvement on the pocket protector side:

`cmd.add(decrypt_domain, posargs={'count': 1, 'provides': 'domain_name'})`

became

`cmd.add(decrypt_domain, posargs={'count': 1, 'name': 'domain_name'})`
